### PR TITLE
Switching dependencies back to PyPi install away from wheels.

### PR DESCRIPTION
**Pull request by nate-axonius**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
* Switched the dependency system from wheels back to PyPi.
* Removed unndeeded wheels from the repo.

---
Thanks for contributing!

### CODE REVIEW

**Comment by pdesai-crest** [comment]
Hello @nate-axonius 

As per the PR, you are removing the wheel files. You have added PyPi instead. 
Now, as per our best practice we are not doing that. We are using wheel files, not PyPi.

Please tell us what is the reason behind wheel files removal and PyPi addition.

**Comment by pdesai-crest** [comment]
> Hello @nate-axonius
> 
> As per the PR, you are removing the wheel files. You have added PyPi instead. Now, as per our best practice we are not doing that. We are using wheel files, not PyPi.
> 
> Please tell us what is the reason behind wheel files removal and PyPi addition.

Hello @nate-axonius 
Can you please look above point and revert back ??

**Comment by nate-axonius** [comment]
@pdesai-crest 

Our integration does not really have to change often unless we are building in new features. However, we update our python library regularly. Sometimes multiple times in a day. Using PYPI allows our customers to always be able to install the latest version of our library to maintain compatibility with the server even when there are no changes needed to the integration.

Also,
Your documentation says nothing about this not being allowed. In fact it says the opposite and says it is still a valid way to specify dependencies: https://docs.splunk.com/Documentation/Phantom/4.10.7/DevelopApps/Metadata#Specifying_pip_dependencies

**Comment by pdesai-crest** [comment]
Hello @nate-axonius 
As you have added PyPi and remove wheel files. This is comparatively major change. So ideally Major or minor version of app should be changed, So you have updated app version from 2.1.2 to 2.1.3
So basically you have updated patch version. As per the changes, we think that you should change minor or major version. As per you, is it okay to update only the patch version ? or can you change minor or major version??

Also please update the value of latest tested version value in json file if possible.

If you have any query/doubts please let us know.

**Comment by pdesai-crest** [comment]
> Hello @nate-axonius As you have added PyPi and remove wheel files. This is comparatively major change. So ideally Major or minor version of app should be changed, So you have updated app version from 2.1.2 to 2.1.3 So basically you have updated patch version. As per the changes, we think that you should change minor or major version. As per you, is it okay to update only the patch version ? or can you change minor or major version??
> 
> Also please update the value of latest tested version value in json file if possible.
> 
> If you have any query/doubts please let us know.

Hello @nate-axonius 

Please look into above points.

**Comment by nate-axonius** [comment]
@pdesai-crest Ok sounds good thanks. I'll bump the version file and updated the JSON.

**Review by splunk-jessica — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
